# Source manjaro-zsh-configuration
if [[ -e /usr/share/zsh/manjaro-zsh-config ]]; then
  source /usr/share/zsh/manjaro-zsh-config
fi

source ~/.local/share/setup/defaults/zsh/rc

# Editor used by CLI
export EDITOR="nano"
export SUDO_EDITOR="$EDITOR"
